<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Inventec.Common.SignLibrary</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>5</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="DevExpress.XtraEditors.v15.2" />
    <Reference Include="System.Net.Http" />
    <Reference Include="DevExpress.Docs.v15.2" />
    <Reference Include="Aspose.Cells" />
    <Reference Include="DevExpress.RichEdit.v15.2.Core" />
    <Reference Include="DevExpress.Printing.v15.2.Core" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="DevExpress.Utils.v15.2" />
    <Reference Include="DevExpress.XtraGrid.v15.2" />
    <Reference Include="DevExpress.Data.v15.2" />
    <Reference Include="EMR.TDO" />
    <Reference Include="EMR.EFMODEL" />
    <Reference Include="DevExpress.XtraLayout.v15.2" />
    <Reference Include="DevExpress.XtraTreeList.v15.2" />
    <Reference Include="System.Core" />
    <Reference Include="Inventec.Common.Controls.EditorLoader" />
    <Reference Include="Inventec.Desktop.Common.Controls.ValidationRule" />
    <Reference Include="DevExpress.XtraBars.v15.2" />
    <Reference Include="Aspose.Pdf" />
    <Reference Include="CARD.WCF.DCO" />
    <Reference Include="CARD.WCF.Client.FingerprintClient" />
    <Reference Include="EMR.Filter" />
    <Reference Include="itextsharp" />
    <Reference Include="EMR.SDO" />
    <Reference Include="DevExpress.XtraPdfViewer.v15.2" />
    <Reference Include="Microsoft.ReportViewer.WinForms" />
    <Reference Include="DevExpress.Pdf.v15.2.Drawing" />
    <Reference Include="GemBox.Pdf" />
    <Reference Include="DevExpress.Pdf.v15.2.Core" />
    <Reference Include="DevExpress.XtraRichEdit.v15.2" />
    <Reference Include="Inventec.Common.SignFile">
      <HintPath>..\..\New folder\Inventec.Common.SignFile.dll</HintPath>
    </Reference>
    <Reference Include="EMR.WCF.DCO" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Configuration" />
    <Reference Include="Inventec.Common.Logging" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="System.Net.Http.Formatting" />
    <Reference Include="System.Web" />
    <Reference Include="DevExpress.Spreadsheet.v15.2.Core" />
    <Reference Include="DevExpress.Images.v15.2" />
    <Reference Include="Inventec.UC.Login" />
    <Reference Include="Inventec.Token.ClientSystem" />
  </ItemGroup>
</Project>