namespace Inventec.Common.SignLibrary
{
	internal class EmrConfigKeys
	{
		internal const string EMR__EMR_SIGN__USING_USBTOKENDEVICE__OPTION = "EMR.EMR_SIGN.USING_USBTOKENDEVICE.OPTION";

		internal const string LIBRARY__EMRGENERATE__SIGNTYPE = "HIS.Desktop.Plugins.Library.EmrGenerate.SignType";

		internal const string EMR__EMR_SIGN_SIGNING_OPTION = "EMR.EMR_SIGN.SIGNING_OPTION";

		internal const string EMR__EMR_DOCUMENT__PATIENT_SIGN__OPTION = "EMR.EMR_DOCUMENT.PATIENT_SIGN.OPTION";

		internal const string EMR__EMR_SIGN__PLACE_SIGN_OPTION = "EMR.EMR_SIGN.PLACE_SIGN_OPTION";

		internal const string EMR_VIEW_PACS_URL_FORMAT = "EMR.VIEW_PACS_URL_FORMAT";

		internal const string EMR__EMR_DOCUMENT__DULICATE_HIS_CODE__WARNING_OPTION = "EMR.EMR_DOCUMENT.DULICATE_HIS_CODE.WARNING_OPTION";

		internal const string PRINT_USING_WARTERMARK__OPTION = "EMR.DOCUMENT.PRINT_USING_WARTERMARK.OPTION";

		internal const string WARTERMARK__VALUE_OPTION = "EMR.EMR_DOCUMENT.WARTERMARK.VALUE_OPTION";

		internal const string SIGN_DISPLAY_OPTION = "EMR.EMR_SIGN.SIGN_DISPLAY_OPTION";

		internal const string PRINT_OPTION = "EMR.EMR_SIGN.PRINT_OPTION";

		internal const string PRINT_LIBIARY_OPTION = "EMR.EMR_SIGN.PRINT_LIBIARY_OPTION";

		internal const string SIGNATURE_APPEARANCE_OPTION = "EMR.EMR_SIGN.SIGNATURE_APPEARANCE_OPTION";

		internal const string SPLIT_PDF_KEY = "EMR.EMR_SIGN.SPLIT_PDF_KEY";

		internal const string IS_NOT_SHOWING_SIGN_INFORMATION = "EMR.IS_NOT_SHOWING_SIGN_INFORMATION";

		internal const string IS_SHOW_WATER_MARK = "EMR.EMR_SIGN.IS_SHOW_WATER_MARK";

		internal const string SIGN_INFO_DISPLAY_OPTION = "EMR.EMR_SIGN.SIGN_INFO_DISPLAY_OPTION";

		internal const string INTERGRATE_SYS_BASE_URI = "EMR.INTERGRATE_SYS_BASE_URI";

		internal const string INTERGRATE_SYS_API = "EMR.INTERGRATE_SYS_API";

		internal const string LICENSE_KEY__APOSE = "LICENSE_KEY__APOSE";

		internal const string EMR__EMR_SIGN__PATIENT_SIGN__OPTION = "EMR.EMR_SIGN.PATIENT_SIGN.OPTION";

		internal const string EMR__EMR_SIGN__SIGN_BOARD__OPTION = "EMR.EMR_SIGN.SIGN_BOARD.OPTION";

		internal const string EMR__EMR_SIGN__SIGN_DESCRIPTION_INFO__OPTION = "EMR.EMR_SIGN.SIGN_DESCRIPTION_INFO.OPTION";

		internal const string EMR_HSM_INTEGRATE_OPTION = "EMR.HSM.INTEGRATE_OPTION";

		internal const string EMR_EMR_SIGNER_AUTO_UPDATE_SIGN_IMAGE = "EMR.EMR_SIGNER.AUTO_UPDATE_SIGN_IMAGE";

		internal const string EMR_EMR_DOCUMENT_PATIENT_SIGN_FIRST_OPTION = "EMR.EMR_DOCUMENT.PATIENT_SIGN_FIRST.OPTION";

		internal const string SIGN_CERTIFICATE_OPTION = "EMR.EMR_PATIENT.SIGN_CERTIFICATE.OPTION";

		internal const string EMR_EMR_BUSINESS_SHOW_ALL_TEMPLATES = "EMR.EMR_BUSINESS.SHOW_ALL_TEMPLATES";

		internal static string EMR_EMR_SIGN_CONNECT_DEVICE_TYPE_OPTION = "EMR.EMR_SIGN.CONNECT_DEVICE_TYPE_OPTION";
	}
}
