<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Inventec.Common.SignFile</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>5</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="itextsharp" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Security" />
    <Reference Include="System.IdentityModel.Tokens.Jwt" />
    <Reference Include="Microsoft.IdentityModel.Tokens" />
    <Reference Include="System.Core" />
    <Reference Include="Inventec.Common.Logging" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>