//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventec.Common.SignLibrary.ServiceSign {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSign.ISignProcessor", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ISignProcessor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignProcessor/SignExecute", ReplyAction="http://tempuri.org/ISignProcessor/SignExecuteResponse")]
        EMR.WCF.DCO.WcfSignResultDCO SignExecute(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignProcessor/SignExecute", ReplyAction="http://tempuri.org/ISignProcessor/SignExecuteResponse")]
        System.Threading.Tasks.Task<EMR.WCF.DCO.WcfSignResultDCO> SignExecuteAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignProcessor/GetSerialNumber", ReplyAction="http://tempuri.org/ISignProcessor/GetSerialNumberResponse")]
        EMR.WCF.DCO.WcfSignResultDCO GetSerialNumber(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignProcessor/GetSerialNumber", ReplyAction="http://tempuri.org/ISignProcessor/GetSerialNumberResponse")]
        System.Threading.Tasks.Task<EMR.WCF.DCO.WcfSignResultDCO> GetSerialNumberAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignProcessorChannel : Inventec.Common.SignLibrary.ServiceSign.ISignProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignProcessorClient : System.ServiceModel.ClientBase<Inventec.Common.SignLibrary.ServiceSign.ISignProcessor>, Inventec.Common.SignLibrary.ServiceSign.ISignProcessor {
        
        public SignProcessorClient() {
        }
        
        public SignProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EMR.WCF.DCO.WcfSignResultDCO SignExecute(string data) {
            return base.Channel.SignExecute(data);
        }
        
        public System.Threading.Tasks.Task<EMR.WCF.DCO.WcfSignResultDCO> SignExecuteAsync(string data) {
            return base.Channel.SignExecuteAsync(data);
        }
        
        public EMR.WCF.DCO.WcfSignResultDCO GetSerialNumber(string data) {
            return base.Channel.GetSerialNumber(data);
        }
        
        public System.Threading.Tasks.Task<EMR.WCF.DCO.WcfSignResultDCO> GetSerialNumberAsync(string data) {
            return base.Channel.GetSerialNumberAsync(data);
        }
    }
}
